name: Generate ASCII Art

on: push

jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay
        run: sudo apt install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON......RAAWR" >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

    test_job_2:
      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Verify file content
        run: grep -i "dragon" dragon.txt

    deploy_job_3:
      needs: [build_job_1, test_job_2]
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying ... .. .